const constants={
// Table Names
CAR_PART_TABLE:"AUTO_CAR_PART",
VEHICLE_TABLE:"AUTO_VEHICLE",
USER_TABLE:"AUTO_USER",
ORDER_TABLE:"AUTO_ORDER",
PAYMENT_TABLE:"AUTO_PAYMENT",
PROMOTION_TABLE:"AUTO_PROMOTION",
COMMENT_TABLE:"AUTO_COMMENT",
REVIEW_TABLE:"AUTO_REVIEW",
SUCURSAL_TABLE:"AUTO_SUCURSAL",
PROFILE_TABLE:"AUTO_PROFILE",
LOGININFO_TABLE:"AUTO_LOGININFO",
STOCK_TABLE:"AUTO_STOCK",
VISIT_TABLE:"AUTO_VISITS",
TOP_RATED_TABLE:"AUTO_TOP_RATED",
BEST_SELLER_TABLE:"AUTO_BEST_SELLER",
SPECIAL_OFFER_TABLE:"AUTO_SPECIAL_OFFER",
NEW_ARRIVALS_TABLE:"AUTO_NEW_ARRIVALS",
POPULAR_CATEGORY_TABLE:"AUTO_POPULAR_CATEGORY",
POPULAR_PRODUCT_TABLE:"AUTO_POPULAR_PRODUCT",
CLIENT_TABLE:"AUTO_CLIENT",
WISH_LIST_TABLE:"AUTO_WISH_LIST",
AUDIT_TABLE:"AUTO_AUDIT",

}

module.exports=constants;