const constants={
// Table Names
CAR_PART_TABLE:"AUTO_CAR_PART",
VEHICLE_TABLE:"AUTO_VEHICLE",
USER_TABLE:"AUTO_USER",
ORDER_TABLE:"AUTO_ORDER",
PAYMENT_TABLE:"AUTO_PAYMENT",
PROMOTION_TABLE:"AUTO_PROMOTION",
COMMENT_TABLE:"AUTO_COMMENT",
REVIEW_TABLE:"AUTO_REVIEW",
SUCURSAL_TABLE:"AUTO_SUCURSAL",
PROFILE_TABLE:"AUTO_PROFILE",
LOGININFO_TABLE:"AUTO_LOGININFO"

}

module.exports=constants;